### ISSUE TITLE
Happy repository

### ISSUE THREAD

**Issue by tiagolobao** [raspiduino/arduino-shell#1]
Seniors told me that to be a developer I should be depressed.
This repository and your profile are defying this principle. That is making me confused.

![image](https://user-images.githubusercontent.com/15076325/187948887-c945f698-f132-425f-a295-4f1204c9db97.png)

**Comment by raspiduino** [comment]
Thank you for taking a look at this repo!

The first thing I was surprised about is that this issue is not opened by a fake / clone account for spamming purpose.

Btw, I'm not a developer, I'm just a normal person with coding as a hobby.

It has been 2 years since I last touched this repo, and I now I think it's silly to write this shell, since it doesn't do much things at all lmao :))

As a hobbyist, I love doing silly things :)) As you can see on my profile, **none** of my repo are for serious purpose.

IMHO (I'm not a real dev, so I am not sure if the things I said is good or not), whatever you want to do, you should have the interest in that thing, instead of being depressed.

Btw how did you find my repo, I really want to know :))

Again, thank you and have a good day!

**Comment by tiagolobao** [comment]
Hey :)

Ahahah I'm a "professional software engineer bla bla bla", and I love my job, this depression thing is a common joke among developers but I disagree!!
So I actually I thought really interesting the way you coded haahha.

I was looking for a library/code for my current project (also arduino related), because I want to create a CLI and I wanted to have some basis and not do it completely from zero (to not reinvent the wheel)

Thank u too!

**Comment by raspiduino** [comment]
Lmao, I know I write bad code :))

Thank you too for taking a look at my repo and my profile :))

**Comment by tiagolobao** [comment]
hahaha no problem! ^^
Happy coding!

**Comment by raspiduino** [comment]
Happy coding too!
